# Provider discovery is driven by validated v2 bindings, never inferred names.
include_guard(GLOBAL)
set(_OBCX_PACKAGE_PROVIDER_MODULE_DIR "${CMAKE_CURRENT_LIST_DIR}")

function(_obcx_json_string OUT VALUE)
  string(REPLACE "\\" "\\\\" _value "${VALUE}")
  string(REPLACE "\"" "\\\"" _value "${_value}")
  string(REPLACE "\n" "\\n" _value "${_value}")
  string(REPLACE "\r" "\\r" _value "${_value}")
  string(REPLACE "\t" "\\t" _value "${_value}")
  set(${OUT} "\"${_value}\"" PARENT_SCOPE)
endfunction()

function(_obcx_json_array OUT)
  set(_array "[]")
  foreach(_value IN LISTS ARGN)
    string(JSON _length LENGTH "${_array}")
    _obcx_json_string(_quoted "${_value}")
    string(JSON _array SET "${_array}" ${_length} "${_quoted}")
  endforeach()
  set(${OUT} "${_array}" PARENT_SCOPE)
endfunction()

function(_obcx_json_list OUT DOCUMENT)
  set(_path ${ARGN})
  string(JSON _count LENGTH "${DOCUMENT}" ${_path})
  set(_items)
  if(_count GREATER 0)
    math(EXPR _last "${_count} - 1")
    foreach(_index RANGE 0 ${_last})
      string(JSON _item GET "${DOCUMENT}" ${_path} ${_index})
      list(APPEND _items "${_item}")
    endforeach()
  endif()
  set(${OUT} "${_items}" PARENT_SCOPE)
endfunction()

function(_obcx_property OUT TARGET_NAME PROPERTY_NAME)
  get_property(_set TARGET "${TARGET_NAME}" PROPERTY "${PROPERTY_NAME}" SET)
  if(_set)
    get_target_property(_value "${TARGET_NAME}" "${PROPERTY_NAME}")
  else()
    set(_value "")
  endif()
  set(${OUT} "${_value}" PARENT_SCOPE)
endfunction()

function(_obcx_observe_provider_target OUT TARGET_NAME)
  if(NOT TARGET "${TARGET_NAME}")
    message(FATAL_ERROR "[OBCX Packages] Missing declared provider target ${TARGET_NAME}")
  endif()
  _obcx_property(_type "${TARGET_NAME}" TYPE)
  _obcx_property(_includes "${TARGET_NAME}" INTERFACE_INCLUDE_DIRECTORIES)
  # SYSTEM_INCLUDE_DIRECTORIES only classifies existing include paths; it does
  # not add search directories. Inspect actual INCLUDE_DIRECTORIES instead.
  list(REMOVE_DUPLICATES _includes)
  set(_locations)
  _obcx_property(_imported "${TARGET_NAME}" IMPORTED)
  if(_imported)
    _obcx_property(_configurations "${TARGET_NAME}" IMPORTED_CONFIGURATIONS)
    set(_properties IMPORTED_LOCATION IMPORTED_IMPLIB)
    foreach(_configuration IN LISTS _configurations)
      string(TOUPPER "${_configuration}" _upper)
      list(APPEND _properties "IMPORTED_LOCATION_${_upper}" "IMPORTED_IMPLIB_${_upper}")
    endforeach()
    foreach(_property IN LISTS _properties)
      _obcx_property(_location "${TARGET_NAME}" "${_property}")
      if(NOT _location STREQUAL "")
        list(APPEND _locations "${_location}")
      endif()
    endforeach()
    list(REMOVE_DUPLICATES _locations)
  endif()
  _obcx_json_string(_name_json "${TARGET_NAME}")
  _obcx_json_string(_type_json "${_type}")
  _obcx_json_array(_locations_json ${_locations})
  _obcx_json_array(_includes_json ${_includes})
  set(${OUT}
      "{\"name\":${_name_json},\"type\":${_type_json},\"locations\":${_locations_json},\"include_directories\":${_includes_json}}"
      PARENT_SCOPE)
endfunction()

function(obcx_find_declared_provider BINDING WORKSPACE STATE_DIR)
  if(NOT ARGC EQUAL 3)
    message(FATAL_ERROR "obcx_find_declared_provider requires binding, workspace and state directory")
  endif()
  find_package(Python3 3.11 COMPONENTS Interpreter REQUIRED)
  string(JSON _id GET "${BINDING}" id)
  if(NOT _id MATCHES "^[a-z0-9]+([._-][a-z0-9]+)*$")
    message(FATAL_ERROR "[OBCX Packages] Invalid provider identity")
  endif()
  string(JSON _kind GET "${BINDING}" kind)
  string(JSON _package GET "${BINDING}" package)
  string(JSON _probe GET "${BINDING}" version_probe kind)
  _obcx_json_list(_targets "${BINDING}" targets)
  _obcx_json_list(_components "${BINDING}" components)
  file(MAKE_DIRECTORY "${STATE_DIR}")
  set(_binding_file "${STATE_DIR}/${_id}.binding.json")
  set(_observed_file "${STATE_DIR}/${_id}.observed.json")
  file(WRITE "${_binding_file}" "${BINDING}\n")
  execute_process(
    COMMAND "${Python3_EXECUTABLE}" "${_OBCX_PACKAGE_PROVIDER_MODULE_DIR}/package_cmake.py"
            check-environment --binding "${_binding_file}" --workspace "${WORKSPACE}"
            --build-dir "${CMAKE_BINARY_DIR}"
    RESULT_VARIABLE _checked ERROR_VARIABLE _error)
  if(NOT _checked EQUAL 0)
    message(FATAL_ERROR "[OBCX Packages] ${_id} environment rejected before discovery:\n${_error}")
  endif()

  set(_find_args)
  if(_components)
    list(APPEND _find_args COMPONENTS ${_components})
  endif()
  if(_kind STREQUAL "cmake-config" OR _kind STREQUAL "installed-sdk")
    find_package(${_package} CONFIG REQUIRED GLOBAL ${_find_args})
  elseif(_kind STREQUAL "cmake-module")
    find_package(${_package} MODULE REQUIRED GLOBAL ${_find_args})
  elseif(_kind STREQUAL "pkg-config")
    list(LENGTH _targets _target_count)
    if(NOT _target_count EQUAL 1 OR _components)
      message(FATAL_ERROR "[OBCX Packages] pkg-config requires one explicit target and no components")
    endif()
    list(GET _targets 0 _target)
    if(NOT _target MATCHES "^PkgConfig::([A-Za-z_][A-Za-z0-9_]*)$")
      message(FATAL_ERROR "[OBCX Packages] pkg-config target must explicitly name PkgConfig::<prefix>")
    endif()
    set(_prefix "${CMAKE_MATCH_1}")
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(${_prefix} REQUIRED IMPORTED_TARGET GLOBAL "${_package}")
  elseif(_kind STREQUAL "workspace-sdk")
    foreach(_target IN LISTS _targets)
      if(NOT TARGET "${_target}")
        message(FATAL_ERROR "[OBCX Packages] Workspace SDK target ${_target} does not exist")
      endif()
      _obcx_property(_imported "${_target}" IMPORTED)
      if(_imported)
        message(FATAL_ERROR "[OBCX Packages] workspace-sdk cannot bind an installed target")
      endif()
    endforeach()
  else()
    message(FATAL_ERROR "[OBCX Packages] Unsupported explicit provider kind ${_kind}")
  endif()

  set(_actual_version "")
  if(_probe STREQUAL "cmake-variable")
    string(JSON _variable GET "${BINDING}" version_probe name)
    if(DEFINED ${_variable})
      set(_actual_version "${${_variable}}")
    endif()
  elseif(_probe STREQUAL "target-property")
    string(JSON _target GET "${BINDING}" version_probe target)
    string(JSON _property GET "${BINDING}" version_probe property)
    if(NOT TARGET "${_target}")
      message(FATAL_ERROR "[OBCX Packages] Missing version-probe target ${_target}")
    endif()
    _obcx_property(_actual_version "${_target}" "${_property}")
  elseif(_probe STREQUAL "pkg-config")
    if(NOT _kind STREQUAL "pkg-config")
      message(FATAL_ERROR "[OBCX Packages] pkg-config probe requires pkg-config discovery")
    endif()
    set(_actual_version "${${_prefix}_VERSION}")
  elseif(NOT _probe STREQUAL "receipt")
    message(FATAL_ERROR "[OBCX Packages] Unsupported explicit version probe ${_probe}")
  endif()

  set(_target_json "[]")
  foreach(_target IN LISTS _targets)
    if(NOT TARGET "${_target}")
      message(FATAL_ERROR "[OBCX Packages] Missing declared provider target ${_target}")
    endif()
    _obcx_property(_imported "${_target}" IMPORTED)
    if(NOT _kind STREQUAL "workspace-sdk" AND NOT _imported)
      message(FATAL_ERROR "[OBCX Packages] External provider ${_id} must expose imported targets")
    endif()
    _obcx_observe_provider_target(_record "${_target}")
    string(JSON _length LENGTH "${_target_json}")
    string(JSON _target_json SET "${_target_json}" ${_length} "${_record}")
  endforeach()
  _obcx_json_string(_id_json "${_id}")
  _obcx_json_string(_version_json "${_actual_version}")
  file(WRITE "${_observed_file}"
       "{\"id\":${_id_json},\"version\":${_version_json},\"targets\":${_target_json}}\n")
  execute_process(
    COMMAND "${Python3_EXECUTABLE}" "${_OBCX_PACKAGE_PROVIDER_MODULE_DIR}/package_cmake.py"
            verify-provider --binding "${_binding_file}" --observed "${_observed_file}"
            --workspace "${WORKSPACE}" --build-dir "${CMAKE_BINARY_DIR}"
            --output "${STATE_DIR}/${_id}.verified.json"
    RESULT_VARIABLE _verified ERROR_VARIABLE _error)
  if(NOT _verified EQUAL 0)
    message(FATAL_ERROR "[OBCX Packages] ${_id} verification failed:\n${_error}")
  endif()
  set_property(GLOBAL APPEND PROPERTY OBCX_VERIFIED_PROVIDERS "${_id}")
  set_property(GLOBAL PROPERTY "OBCX_PROVIDER_${_id}_TARGETS" "${_targets}")
  set_property(GLOBAL PROPERTY "OBCX_PROVIDER_${_id}_BINDING" "${BINDING}")
  set_property(GLOBAL PROPERTY "OBCX_PROVIDER_${_id}_OBSERVED" "${_observed_file}")
endfunction()
