# v2 explicit workspace resolver and graph consumer. No downloads or version selection.
include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/OBCXPackageProviders.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/OBCXActorIdentity.cmake")
set(_OBCX_PACKAGES_MODULE_DIR "${CMAKE_CURRENT_LIST_DIR}")
set(_OBCX_AUDIT_PROPERTIES TYPE SOURCE_DIR BINARY_DIR POSITION_INDEPENDENT_CODE
    CXX_STANDARD CXX_EXTENSIONS OUTPUT_NAME PREFIX IMPORTED BUILD_RPATH
    MANUALLY_ADDED_DEPENDENCIES LINK_LIBRARIES INTERFACE_LINK_LIBRARIES SOURCES INTERFACE_SOURCES
    INCLUDE_DIRECTORIES INTERFACE_INCLUDE_DIRECTORIES INTERFACE_SYSTEM_INCLUDE_DIRECTORIES
    LINK_DIRECTORIES INTERFACE_LINK_DIRECTORIES LINK_OPTIONS INTERFACE_LINK_OPTIONS
    COMPILE_OPTIONS INTERFACE_COMPILE_OPTIONS COMPILE_DEFINITIONS INTERFACE_COMPILE_DEFINITIONS)

function(_obcx_package_command)
  get_property(_python GLOBAL PROPERTY OBCX_PACKAGE_PYTHON)
  execute_process(COMMAND "${_python}" "${_OBCX_PACKAGES_MODULE_DIR}/package_cmake.py" ${ARGN}
                  RESULT_VARIABLE _status ERROR_VARIABLE _error)
  if(NOT _status EQUAL 0)
    message(FATAL_ERROR "[OBCX Packages] ${_error}")
  endif()
endfunction()

function(_obcx_record_package NODE)
  string(JSON _id GET "${NODE}" id)
  set_property(GLOBAL APPEND PROPERTY OBCX_PACKAGE_IDS "${_id}")
  set_property(GLOBAL PROPERTY "OBCX_PACKAGE_${_id}" "${NODE}")
  string(JSON _source GET "${NODE}" source_dir)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_source}/package.toml")
  foreach(_field target export_target)
    string(JSON _name GET "${NODE}" metadata artifact ${_field})
    if(TARGET "${_name}")
      message(FATAL_ERROR "[OBCX Packages] ${_id}: artifact/export collides with existing target ${_name}")
    endif()
  endforeach()
endfunction()

function(_obcx_target_record OUT NAME)
  set(_record "{}")
  set(_properties ${_OBCX_AUDIT_PROPERTIES} VERSION SOVERSION)
  get_property(_graph GLOBAL PROPERTY OBCX_PACKAGE_GRAPH)
  string(JSON _count LENGTH "${_graph}" providers)
  if(_count GREATER 0)
    math(EXPR _last "${_count} - 1")
    foreach(_index RANGE 0 ${_last})
      string(JSON _probe GET "${_graph}" providers ${_index} version_probe)
      string(JSON _kind GET "${_probe}" kind)
      if(_kind STREQUAL "target-property")
        string(JSON _property GET "${_probe}" property)
        list(APPEND _properties "${_property}")
      endif()
    endforeach()
  endif()
  list(REMOVE_DUPLICATES _properties)
  foreach(_property IN LISTS _properties)
    _obcx_property(_value "${NAME}" "${_property}")
    _obcx_json_string(_json "${_value}")
    string(JSON _record SET "${_record}" "${_property}" "${_json}")
  endforeach()
  _obcx_observe_provider_target(_observed "${NAME}")
  string(JSON _locations GET "${_observed}" locations)
  string(JSON _record SET "${_record}" locations "${_locations}")
  set(${OUT} "${_record}" PARENT_SCOPE)
endfunction()

function(_obcx_canonical OUT NAME)
  _obcx_property(_alias "${NAME}" ALIASED_TARGET)
  if(_alias)
    set(${OUT} "${_alias}" PARENT_SCOPE)
  else()
    set(${OUT} "${NAME}" PARENT_SCOPE)
  endif()
endfunction()

function(_obcx_capture_provider NAME)
  _obcx_canonical(_name "${NAME}")
  get_property(_visited GLOBAL PROPERTY OBCX_CURRENT_PROVIDER_CLOSURE)
  if(_name IN_LIST _visited)
    return()
  endif()
  set_property(GLOBAL APPEND PROPERTY OBCX_CURRENT_PROVIDER_CLOSURE "${_name}")
  get_property(_known GLOBAL PROPERTY OBCX_PROVIDER_CLOSURE)
  _obcx_target_record(_record "${_name}")
  string(SHA256 _key "${_name}")
  if(_name IN_LIST _known)
    get_property(_before GLOBAL PROPERTY "OBCX_PROVIDER_SNAPSHOT_${_key}")
    if(NOT _before STREQUAL _record)
      message(FATAL_ERROR "[OBCX Packages] Conflicting provider definitions for ${_name}")
    endif()
  else()
    set_property(GLOBAL APPEND PROPERTY OBCX_PROVIDER_CLOSURE "${_name}")
    set_property(GLOBAL PROPERTY "OBCX_PROVIDER_SNAPSHOT_${_key}" "${_record}")
  endif()
  # Capture referenced existing targets before any package runs. This does not
  # authorize consumers to link those internal targets directly.
  string(REGEX REPLACE "\\$<[A-Za-z0-9_]+:" "" _references "${_record}")
  string(REGEX MATCHALL "[A-Za-z_][A-Za-z0-9_.:+-]*" _tokens "${_references}")
  foreach(_token IN LISTS _tokens)
    if(TARGET "${_token}")
      _obcx_capture_provider("${_token}")
    endif()
  endforeach()
endfunction()

function(_obcx_load_provider BINDING)
  get_property(_workspace GLOBAL PROPERTY OBCX_PACKAGE_WORKSPACE)
  get_property(_state GLOBAL PROPERTY OBCX_PACKAGE_STATE)
  obcx_find_declared_provider("${BINDING}" "${_workspace}" "${_state}/providers")
  _obcx_json_list(_targets "${BINDING}" targets)
  set_property(GLOBAL PROPERTY OBCX_CURRENT_PROVIDER_CLOSURE "")
  foreach(_target IN LISTS _targets)
    _obcx_capture_provider("${_target}")
  endforeach()
  string(JSON _id GET "${BINDING}" id)
  get_property(_members GLOBAL PROPERTY OBCX_CURRENT_PROVIDER_CLOSURE)
  set_property(GLOBAL PROPERTY "OBCX_PROVIDER_${_id}_MEMBERS" "${_members}")
  string(JSON _anchor GET "${BINDING}" provenance path)
  get_filename_component(_anchor "${_anchor}" ABSOLUTE BASE_DIR "${_workspace}")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_anchor}")
  string(JSON _probe GET "${BINDING}" version_probe kind)
  if(_probe STREQUAL "receipt")
    string(JSON _path GET "${BINDING}" version_probe path)
    get_filename_component(_path "${_path}" ABSOLUTE BASE_DIR "${_workspace}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_path}")
  endif()
endfunction()

function(_obcx_configure_package ID SOURCE)
  get_property(_node GLOBAL PROPERTY "OBCX_PACKAGE_${ID}")
  get_property(_state GLOBAL PROPERTY OBCX_PACKAGE_STATE)
  set(OBCX_CURRENT_PACKAGE "${ID}")
  get_property(_graph GLOBAL PROPERTY OBCX_PACKAGE_GRAPH)
  string(JSON OBCX_PACKAGE_PROFILE GET "${_graph}" profile)
  string(JSON _abi GET "${_node}" metadata compatibility cxx11_abi)
  include(CheckCXXSourceCompiles)
  set(_probe "OBCX_PACKAGE_ABI_${_abi}")
  check_cxx_source_compiles("#include <string>\n#ifndef __GLIBCXX__\n#error libstdc++ required\n#endif\nstatic_assert(_GLIBCXX_USE_CXX11_ABI == ${_abi});\nint main() {}" "${_probe}")
  if(NOT ${_probe})
    message(FATAL_ERROR "[OBCX Packages] ${ID}: toolchain stdlib/C++ ABI mismatch")
  endif()
  add_subdirectory("${SOURCE}" "${_state}/build/${ID}")
endfunction()

function(_obcx_apply_dependencies TARGET_NAME ROLE)
  get_property(_graph GLOBAL PROPERTY OBCX_PACKAGE_GRAPH)
  string(JSON _count LENGTH "${_graph}" edges)
  _obcx_property(_type "${TARGET_NAME}" TYPE)
  if(_count EQUAL 0 OR _type STREQUAL "UTILITY")
    return()
  endif()
  math(EXPR _last "${_count} - 1")
  foreach(_index RANGE 0 ${_last})
    string(JSON _edge GET "${_graph}" edges ${_index})
    string(JSON _owner GET "${_edge}" from)
    string(JSON _kind GET "${_edge}" kind)
    string(JSON _scope GET "${_edge}" scope)
    if(NOT _owner STREQUAL OBCX_CURRENT_PACKAGE OR _kind STREQUAL "actors")
      continue()
    endif()
    if(_scope STREQUAL "test" AND NOT ROLE STREQUAL "test")
      continue()
    endif()
    string(JSON _visibility GET "${_edge}" visibility)
    string(TOUPPER "${_visibility}" _visibility)
    if(_type STREQUAL "INTERFACE_LIBRARY")
      set(_visibility INTERFACE)
    endif()
    _obcx_json_list(_targets "${_edge}" targets)
    target_link_libraries("${TARGET_NAME}" ${_visibility} ${_targets})
  endforeach()
endfunction()

function(_obcx_register_target TARGET_NAME ROLE)
  if(NOT DEFINED OBCX_CURRENT_PACKAGE OR NOT TARGET "${TARGET_NAME}")
    message(FATAL_ERROR "[OBCX Packages] Register targets only inside their prepared package")
  endif()
  get_property(_node GLOBAL PROPERTY "OBCX_PACKAGE_${OBCX_CURRENT_PACKAGE}")
  string(JSON _root GET "${_node}" source_dir)
  _obcx_property(_source "${TARGET_NAME}" SOURCE_DIR)
  cmake_path(IS_PREFIX _root "${_source}" NORMALIZE _owned)
  get_property(_state GLOBAL PROPERTY OBCX_PACKAGE_STATE)
  set(_binary_root "${_state}/build/${OBCX_CURRENT_PACKAGE}")
  _obcx_property(_binary "${TARGET_NAME}" BINARY_DIR)
  cmake_path(IS_PREFIX _binary_root "${_binary}" NORMALIZE _owned_binary)
  _obcx_property(_imported "${TARGET_NAME}" IMPORTED)
  _obcx_property(_alias "${TARGET_NAME}" ALIASED_TARGET)
  _obcx_property(_owner "${TARGET_NAME}" OBCX_PACKAGE_OWNER)
  if(NOT _owned OR NOT _owned_binary OR _imported OR _alias OR _owner)
    message(FATAL_ERROR "[OBCX Packages] ${TARGET_NAME}: invalid or duplicate target ownership")
  endif()
  get_property(_graph GLOBAL PROPERTY OBCX_PACKAGE_GRAPH)
  string(JSON _profile GET "${_graph}" profile)
  if(ROLE STREQUAL "test" AND NOT _profile STREQUAL "tests")
    message(FATAL_ERROR "[OBCX Packages] Test target ${TARGET_NAME} in production profile")
  endif()
  set_target_properties("${TARGET_NAME}" PROPERTIES OBCX_PACKAGE_OWNER "${OBCX_CURRENT_PACKAGE}" OBCX_PACKAGE_ROLE "${ROLE}")
  _obcx_property(_type "${TARGET_NAME}" TYPE)
  if(NOT _type STREQUAL "UTILITY")
    string(JSON _standard GET "${_node}" metadata compatibility cpp_standard)
    if(_type STREQUAL "INTERFACE_LIBRARY")
      target_compile_features("${TARGET_NAME}" INTERFACE "cxx_std_${_standard}")
    else()
      set_target_properties("${TARGET_NAME}" PROPERTIES POSITION_INDEPENDENT_CODE ON
        CXX_STANDARD "${_standard}" CXX_STANDARD_REQUIRED ON CXX_EXTENSIONS OFF)
      target_compile_features("${TARGET_NAME}" PUBLIC "cxx_std_${_standard}")
    endif()
    _obcx_apply_dependencies("${TARGET_NAME}" "${ROLE}")
    string(JSON _kind GET "${_node}" kind)
    if(_kind STREQUAL "actor" AND NOT _type STREQUAL "INTERFACE_LIBRARY")
      string(JSON _actor_name GET "${_node}" metadata actor name)
      string(JSON _actor_version GET "${_node}" metadata package version)
      _obcx_bind_actor_identity("${TARGET_NAME}" "${OBCX_CURRENT_PACKAGE}"
        "${_actor_name}" "${_actor_version}" "${_binary_root}/generated")
    endif()
  endif()
endfunction()

# Internal implementation and test targets are owned, not separate packages.
function(obcx_package_target TARGET_NAME)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "ROLE" "")
  if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES OR NOT ARG_ROLE MATCHES "^(implementation|test)$")
    message(FATAL_ERROR "obcx_package_target requires explicit ROLE implementation|test")
  endif()
  _obcx_register_target("${TARGET_NAME}" "${ARG_ROLE}")
endfunction()

function(_obcx_add_artifact KIND)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "" "SOURCES")
  if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES OR NOT DEFINED OBCX_CURRENT_PACKAGE)
    message(FATAL_ERROR "[OBCX Packages] Artifact helper accepts only SOURCES inside a prepared package")
  endif()
  get_property(_node GLOBAL PROPERTY "OBCX_PACKAGE_${OBCX_CURRENT_PACKAGE}")
  string(JSON _kind GET "${_node}" kind)
  if(NOT _kind STREQUAL KIND)
    message(FATAL_ERROR "[OBCX Packages] Artifact helper disagrees with package kind")
  endif()
  foreach(_field kind name target export_target)
    string(JSON _${_field} GET "${_node}" metadata artifact ${_field})
  endforeach()
  if(_kind STREQUAL "header-only")
    add_library("${_target}" INTERFACE)
    if(ARG_SOURCES)
      target_sources("${_target}" INTERFACE ${ARG_SOURCES})
    endif()
  else()
    if(NOT ARG_SOURCES)
      message(FATAL_ERROR "[OBCX Packages] Compiled artifact requires explicit SOURCES")
    endif()
    if(_kind STREQUAL "static-library")
      add_library("${_target}" STATIC ${ARG_SOURCES})
    else()
      add_library("${_target}" SHARED ${ARG_SOURCES})
    endif()
    set_target_properties("${_target}" PROPERTIES OUTPUT_NAME "${_name}")
  endif()
  add_library("${_export_target}" ALIAS "${_target}")
  _obcx_register_target("${_target}" artifact)
  if(KIND STREQUAL "actor")
    set_target_properties("${_target}" PROPERTIES PREFIX "" LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/actors")
    target_compile_options("${_target}" PRIVATE -freflection)
    include(CheckCXXSourceCompiles)
    string(APPEND CMAKE_REQUIRED_FLAGS " -std=c++26 -freflection")
    check_cxx_source_compiles("#include <meta>\nstatic_assert(__cpp_impl_reflection >= 202506L);\nint main() {}" OBCX_PACKAGE_REFLECTION_SUPPORTED)
    if(NOT OBCX_PACKAGE_REFLECTION_SUPPORTED)
      message(FATAL_ERROR "[OBCX Packages] Actor reflection contract is unsupported")
    endif()
  endif()
endfunction()

function(obcx_add_library)
  _obcx_add_artifact(library ${ARGV})
endfunction()

function(obcx_add_actor)
  _obcx_add_artifact(actor ${ARGV})
endfunction()

function(_obcx_collect_package_directory DIRECTORY OWNER)
  get_property(_imported DIRECTORY "${DIRECTORY}" PROPERTY IMPORTED_TARGETS)
  if(_imported)
    message(FATAL_ERROR "[OBCX Packages] ${OWNER}: package-created imported targets are unowned; declare providers instead")
  endif()
  get_property(_targets DIRECTORY "${DIRECTORY}" PROPERTY BUILDSYSTEM_TARGETS)
  foreach(_target IN LISTS _targets)
    _obcx_property(_owner "${_target}" OBCX_PACKAGE_OWNER)
    if(NOT _owner STREQUAL OWNER)
      message(FATAL_ERROR "[OBCX Packages] ${OWNER}: unregistered target ${_target}")
    endif()
    set_property(GLOBAL APPEND PROPERTY OBCX_OWNED_TARGETS "${_target}")
  endforeach()
  get_property(_children DIRECTORY "${DIRECTORY}" PROPERTY SUBDIRECTORIES)
  foreach(_child IN LISTS _children)
    _obcx_collect_package_directory("${_child}" "${OWNER}")
  endforeach()
endfunction()

function(_obcx_audit_packages)
  get_property(_ids GLOBAL PROPERTY OBCX_PACKAGE_IDS)
  get_property(_state GLOBAL PROPERTY OBCX_PACKAGE_STATE)
  foreach(_id IN LISTS _ids)
    # Binary directories disambiguate a standalone package's bootstrap source
    # from the same source loaded as a verified package subdirectory.
    _obcx_collect_package_directory("${_state}/build/${_id}" "${_id}")
  endforeach()
  get_property(_owned GLOBAL PROPERTY OBCX_OWNED_TARGETS)
  get_property(_providers GLOBAL PROPERTY OBCX_PROVIDER_CLOSURE)
  set(_snapshot "{\"targets\":{},\"aliases\":{},\"binary_roots\":{},\"providers\":{}}")
  get_property(_workspace GLOBAL PROPERTY OBCX_PACKAGE_WORKSPACE)
  _obcx_json_string(_json "${_workspace}")
  string(JSON _snapshot SET "${_snapshot}" workspace "${_json}")
  _obcx_json_string(_json "${CMAKE_BINARY_DIR}")
  string(JSON _snapshot SET "${_snapshot}" build "${_json}")
  foreach(_id IN LISTS _ids)
    _obcx_json_string(_json "${_state}/build/${_id}")
    string(JSON _snapshot SET "${_snapshot}" binary_roots "${_id}" "${_json}")
  endforeach()
  foreach(_target IN LISTS _owned _providers)
    _obcx_target_record(_record "${_target}")
    string(SHA256 _key "${_target}")
    if(_target IN_LIST _providers)
      get_property(_before GLOBAL PROPERTY "OBCX_PROVIDER_SNAPSHOT_${_key}")
      if(NOT _before STREQUAL _record)
        message(FATAL_ERROR "[OBCX Packages] Provider target ${_target} mutated after verification")
      endif()
      set(_owner "@provider")
      set(_role "provider")
    else()
      _obcx_property(_owner "${_target}" OBCX_PACKAGE_OWNER)
      _obcx_property(_role "${_target}" OBCX_PACKAGE_ROLE)
    endif()
    foreach(_field owner role key)
      _obcx_json_string(_json "${_${_field}}")
      string(JSON _record SET "${_record}" "${_field}" "${_json}")
    endforeach()
    string(JSON _snapshot SET "${_snapshot}" targets "${_target}" "${_record}")
    string(REGEX REPLACE "\\$<[A-Za-z0-9_]+:" "" _references "${_record}")
    string(REGEX MATCHALL "[A-Za-z_][A-Za-z0-9_.:+-]*" _tokens "${_references}")
    foreach(_token IN LISTS _tokens)
      if(TARGET "${_token}")
        _obcx_canonical(_actual "${_token}")
        _obcx_json_string(_json "${_actual}")
        string(JSON _snapshot SET "${_snapshot}" aliases "${_token}" "${_json}")
      endif()
    endforeach()
    foreach(_property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES SOURCES INTERFACE_SOURCES
        INCLUDE_DIRECTORIES INTERFACE_INCLUDE_DIRECTORIES INTERFACE_SYSTEM_INCLUDE_DIRECTORIES
        LINK_DIRECTORIES INTERFACE_LINK_DIRECTORIES LINK_OPTIONS INTERFACE_LINK_OPTIONS
        COMPILE_OPTIONS INTERFACE_COMPILE_OPTIONS COMPILE_DEFINITIONS INTERFACE_COMPILE_DEFINITIONS)
      _obcx_property(_raw "${_target}" "${_property}")
      if(_property STREQUAL "INTERFACE_LINK_LIBRARIES")
        # file(GENERATE) has no link context. Preserve native expression
        # evaluation while selecting LINK_ONLY's documented usage/link meaning.
        string(REPLACE "$<LINK_ONLY:" "$<0:" _usage "${_raw}")
        file(GENERATE OUTPUT "${_state}/evaluated/$<CONFIG>/${_key}.INTERFACE_USAGE"
             CONTENT "$<TARGET_GENEX_EVAL:${_target},${_usage}>" TARGET "${_target}")
      endif()
      string(REPLACE "$<LINK_ONLY:" "$<1:" _raw "${_raw}")
      file(GENERATE OUTPUT "${_state}/evaluated/$<CONFIG>/${_key}.${_property}"
           CONTENT "$<TARGET_GENEX_EVAL:${_target},${_raw}>" TARGET "${_target}")
    endforeach()
    _obcx_property(_type "${_target}" TYPE)
    if(_type STREQUAL "OBJECT_LIBRARY")
      file(GENERATE OUTPUT "${_state}/evaluated/$<CONFIG>/${_key}.objects"
           CONTENT "$<TARGET_OBJECTS:${_target}>" TARGET "${_target}")
    endif()
    if(_target IN_LIST _owned AND NOT _type STREQUAL "INTERFACE_LIBRARY")
      add_dependencies("${_target}" obcx_package_audit)
    endif()
  endforeach()
  # Export aliases need recording even when no consumer directly links them.
  foreach(_id IN LISTS _ids)
    get_property(_node GLOBAL PROPERTY "OBCX_PACKAGE_${_id}")
    string(JSON _export GET "${_node}" metadata artifact export_target)
    if(NOT TARGET "${_export}")
      message(FATAL_ERROR "[OBCX Packages] ${_id}: missing export ${_export}")
    endif()
    _obcx_canonical(_actual "${_export}")
    _obcx_json_string(_json "${_actual}")
    string(JSON _snapshot SET "${_snapshot}" aliases "${_export}" "${_json}")
  endforeach()
  get_property(_provider_ids GLOBAL PROPERTY OBCX_VERIFIED_PROVIDERS)
  foreach(_id IN LISTS _provider_ids)
    get_property(_binding GLOBAL PROPERTY "OBCX_PROVIDER_${_id}_BINDING")
    get_property(_members GLOBAL PROPERTY "OBCX_PROVIDER_${_id}_MEMBERS")
    _obcx_json_array(_members_json ${_members})
    get_property(_observed GLOBAL PROPERTY "OBCX_PROVIDER_${_id}_OBSERVED")
    _obcx_json_string(_observed_json "${_observed}")
    string(JSON _snapshot SET "${_snapshot}" providers "${_id}" "{\"binding\":${_binding},\"members\":${_members_json},\"observed\":${_observed_json}}")
    get_property(_targets GLOBAL PROPERTY "OBCX_PROVIDER_${_id}_TARGETS")
    foreach(_target IN LISTS _targets)
      _obcx_canonical(_actual "${_target}")
      _obcx_json_string(_json "${_actual}")
      string(JSON _snapshot SET "${_snapshot}" aliases "${_target}" "${_json}")
    endforeach()
  endforeach()
  file(WRITE "${_state}/targets.json" "${_snapshot}\n")
  _obcx_package_command(audit --graph "${_state}/current-graph.json" --snapshot "${_state}/targets.json")
endfunction()

# Common entry point for core and a package's top-level installed-SDK build.
function(obcx_load_configured_workspace)
  foreach(_name WORKSPACE CACHE MODE STATE_DIR)
    if(NOT DEFINED OBCX_PACKAGES_${_name} OR "${OBCX_PACKAGES_${_name}}" STREQUAL "")
      message(FATAL_ERROR "Explicit OBCX_PACKAGES_${_name} is required; select a preset or supply the option")
    endif()
  endforeach()
  obcx_load_packages(WORKSPACE "${OBCX_PACKAGES_WORKSPACE}"
    CACHE "${OBCX_PACKAGES_CACHE}" MODE "${OBCX_PACKAGES_MODE}"
    STATE_DIR "${OBCX_PACKAGES_STATE_DIR}")
endfunction()

function(obcx_load_packages)
  cmake_parse_arguments(PARSE_ARGV 0 ARG "" "WORKSPACE;CACHE;MODE;STATE_DIR" "")
  if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES)
    message(FATAL_ERROR "[OBCX Packages] Unknown or empty loader arguments")
  endif()
  foreach(_field WORKSPACE CACHE MODE STATE_DIR)
    if(NOT DEFINED ARG_${_field} OR "${ARG_${_field}}" STREQUAL "")
      message(FATAL_ERROR "[OBCX Packages] Explicit ${_field} is required")
    endif()
  endforeach()
  get_property(_loaded GLOBAL PROPERTY OBCX_PACKAGE_STATE)
  if(_loaded)
    message(FATAL_ERROR "[OBCX Packages] Load one workspace graph per CMake build")
  endif()
  if(NOT CMAKE_CONFIGURATION_TYPES AND NOT CMAKE_BUILD_TYPE)
    message(FATAL_ERROR "[OBCX Packages] Select a CMake configuration explicitly")
  endif()
  if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR "[OBCX Packages] Unsupported target platform")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|amd64)$")
    set(_platform linux-x86_64)
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64)$")
    set(_platform linux-arm64)
  else()
    message(FATAL_ERROR "[OBCX Packages] Unsupported target processor")
  endif()
  find_package(Python3 3.11 COMPONENTS Interpreter REQUIRED)
  # Needed by the root-directory deferred callback as well as this function.
  set(Python3_EXECUTABLE "${Python3_EXECUTABLE}" PARENT_SCOPE)
  set_property(GLOBAL PROPERTY OBCX_PACKAGE_PYTHON "${Python3_EXECUTABLE}")
  get_filename_component(_state "${ARG_STATE_DIR}" ABSOLUTE BASE_DIR "${CMAKE_BINARY_DIR}")
  get_filename_component(_manifest "${ARG_WORKSPACE}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  get_filename_component(_workspace "${_manifest}" DIRECTORY)
  if(NOT IS_ABSOLUTE "${ARG_CACHE}")
    message(FATAL_ERROR "[OBCX Packages] CACHE must be an explicit absolute path")
  endif()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_manifest}")
  file(GLOB _tool_sources "${_OBCX_PACKAGES_MODULE_DIR}/obcx_package/*.py")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_tool_sources}
    "${_OBCX_PACKAGES_MODULE_DIR}/package_cmake.py")
  file(MAKE_DIRECTORY "${_state}")
  set_property(GLOBAL PROPERTY OBCX_PACKAGE_STATE "${_state}")
  set_property(GLOBAL PROPERTY OBCX_PACKAGE_WORKSPACE "${_workspace}")
  cmake_file_api(QUERY API_VERSION 1 CODEMODEL 2 TOOLCHAINS 1)
  _obcx_package_command(plan --workspace "${_manifest}"
    --cache "${ARG_CACHE}" --mode "${ARG_MODE}" --build-dir "${CMAKE_BINARY_DIR}"
    --platform "${_platform}" --compiler-id "${CMAKE_CXX_COMPILER_ID}" --compiler-version "${CMAKE_CXX_COMPILER_VERSION}"
    --output "${_state}/plan.cmake" --current-graph "${_state}/current-graph.json")
  include("${_state}/plan.cmake")
  add_custom_target(obcx_package_audit ALL
    COMMAND "${Python3_EXECUTABLE}" "${_OBCX_PACKAGES_MODULE_DIR}/package_cmake.py" audit-generated
      --graph "${_state}/current-graph.json" --snapshot "${_state}/targets.json"
      --evaluated "${_state}/evaluated/$<CONFIG>" --build-dir "${CMAKE_BINARY_DIR}" --configuration "$<CONFIG>"
    VERBATIM)
  cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}" CALL _obcx_audit_packages)
endfunction()
